//! Integration tests against real Amiga Workbench floppy images.
//!
//! These exercise the OFS (Workbench 1.3) and FFS (Workbench 3.1) readers
//! against disks produced by the real operating system, rather than the
//! synthetic images the unit tests build. That distinction matters: the
//! synthetic images were generated by this crate's own writer, so a wrong
//! assumption shared by reader and writer round-tripped happily. Two such
//! bugs were only visible against real disks:
//!
//!   * the file header's data-block table is anchored at the *end* of the
//!     block and grows downwards, not filled from index 0 up — every
//!     extraction returned an empty file;
//!   * `amiga_hash` masked its running value to 31 bits instead of 11
//!     (`0x7FF`), so it named the wrong bucket for all but the shortest
//!     names and most files reported "not found" — while `--list`, which
//!     walks every bucket, listed them fine.
//!
//! The images are not redistributable, so the tests skip themselves when
//! `M68K_WB_DIR` is unset or the files are missing. Point it at a
//! directory of Workbench ADFs to run them:
//!
//! ```text
//! M68K_WB_DIR=/path/to/wb cargo test -p m68k-floppy --test workbench_disks
//! ```

use m68k_floppy::adf::AdfBackend;
use m68k_floppy::amigados::AmigaFs;
use std::path::{Path, PathBuf};

/// Standard double-density Amiga floppy geometry.
const DD_TRACKS: u32 = 80;

fn wb_dir() -> Option<PathBuf> {
    let dir = PathBuf::from(std::env::var_os("M68K_WB_DIR")?);
    dir.is_dir().then_some(dir)
}

fn open(dir: &Path, name: &str) -> Option<AdfBackend> {
    let path = dir.join(name);
    if !path.is_file() {
        return None;
    }
    AdfBackend::open(&path).ok()
}

/// Every file listed in a directory must extract to exactly the byte count
/// the directory entry advertises. This is the check that caught the
/// data-block table bug: listing worked, extraction silently produced
/// zero bytes.
fn assert_all_files_extract(dir: &Path, image: &str) {
    let Some(mut reader) = open(dir, image) else {
        return;
    };
    let mut fs = match AmigaFs::mount(&mut reader, DD_TRACKS) {
        Ok(fs) => fs,
        Err(e) => panic!("{}: mount failed: {}", image, e),
    };
    let root = fs.root_block_num();
    let entries = fs
        .list_dir(root)
        .unwrap_or_else(|e| panic!("{}: list_dir failed: {}", image, e));
    assert!(
        !entries.is_empty(),
        "{}: root directory listed as empty",
        image
    );

    let mut checked = 0;
    for entry in entries {
        if entry.is_dir {
            continue;
        }
        // Look the name back up the way the CLI does, so a lookup
        // regression fails here too rather than only in --extract.
        let found = fs
            .find_entry(root, &entry.name)
            .unwrap_or_else(|e| panic!("{}: find_entry({:?}) failed: {}", image, entry.name, e))
            .unwrap_or_else(|| panic!("{}: {:?} listed but not findable", image, entry.name));
        assert_eq!(
            found.block, entry.block,
            "{}: find_entry({:?}) returned the wrong header block",
            image, entry.name
        );

        let data = fs
            .read_file(entry.block)
            .unwrap_or_else(|e| panic!("{}: read_file({:?}) failed: {}", image, entry.name, e));
        assert_eq!(
            data.len(),
            entry.size as usize,
            "{}: {:?} extracted {} bytes, directory says {}",
            image,
            entry.name,
            data.len(),
            entry.size
        );
        checked += 1;
    }
    assert!(checked > 0, "{}: no files in root to check", image);
}

#[test]
fn workbench_13_ofs_files_extract_at_full_length() {
    let Some(dir) = wb_dir() else { return };
    assert_all_files_extract(&dir, "SYS-WB13-1.ADF");
    assert_all_files_extract(&dir, "SYS-WB13-2.ADF");
}

#[test]
fn workbench_31_ffs_files_extract_at_full_length() {
    let Some(dir) = wb_dir() else { return };
    for n in 1..=6 {
        assert_all_files_extract(&dir, &format!("SYS-WB31-{}.ADF", n));
    }
}

/// The whole disk, not just the root: every file at every depth must
/// extract at its advertised length, and paths must resolve.
///
/// Root-only checks miss the bulk of a Workbench disk — on WB3.1 disk 1
/// the root holds 17 entries while the full tree holds 170.
#[test]
fn every_file_on_every_disk_extracts_at_full_length() {
    let Some(dir) = wb_dir() else { return };
    let images = [
        "SYS-WB13-1.ADF",
        "SYS-WB13-2.ADF",
        "SYS-WB31-1.ADF",
        "SYS-WB31-2.ADF",
        "SYS-WB31-3.ADF",
        "SYS-WB31-4.ADF",
        "SYS-WB31-5.ADF",
        "SYS-WB31-6.ADF",
    ];

    let mut total_files = 0;
    for image in images {
        let Some(mut reader) = open(&dir, image) else {
            continue;
        };
        let mut fs = AmigaFs::mount(&mut reader, DD_TRACKS)
            .unwrap_or_else(|e| panic!("{}: mount failed: {}", image, e));
        let entries = fs
            .walk("", 64)
            .unwrap_or_else(|e| panic!("{}: walk failed: {}", image, e));
        assert!(!entries.is_empty(), "{}: walk found nothing", image);

        for (path, entry) in entries {
            // Every path the walk reports must resolve back to the same
            // block, which exercises multi-component path resolution.
            let resolved = fs
                .resolve_path(&path)
                .unwrap_or_else(|e| panic!("{}: resolve_path({:?}) failed: {}", image, path, e))
                .unwrap_or_else(|| {
                    panic!("{}: walk listed {:?} but it won't resolve", image, path)
                });
            assert_eq!(
                resolved.block, entry.block,
                "{}: resolve_path({:?}) landed on the wrong block",
                image, path
            );

            if entry.is_dir {
                continue;
            }
            let data = fs
                .read_file_at_path(&path)
                .unwrap_or_else(|e| panic!("{}: read {:?} failed: {}", image, path, e));
            assert_eq!(
                data.len(),
                entry.size as usize,
                "{}: {:?} extracted {} bytes, directory says {}",
                image,
                path,
                data.len(),
                entry.size
            );
            total_files += 1;
        }
    }
    assert!(
        total_files > 0,
        "no files checked — are the images present?"
    );
}

/// Spot-check file *contents*, not just lengths, via well-known Amiga
/// magic numbers. A reader that returned the right number of wrong bytes
/// would pass the length check above.
#[test]
fn extracted_files_have_the_expected_magic_numbers() {
    let Some(dir) = wb_dir() else { return };

    // (image, filename, leading bytes)
    let cases: &[(&str, &str, &[u8])] = &[
        // AmigaDOS executable: HUNK_HEADER.
        ("SYS-WB13-2.ADF", "AmigaBASIC", &[0x00, 0x00, 0x03, 0xF3]),
        ("SYS-WB31-3.ADF", "Installer", &[0x00, 0x00, 0x03, 0xF3]),
        // Workbench icon: 0xE310 "DiskObject" magic.
        ("SYS-WB31-1.ADF", "Disk.info", &[0xE3, 0x10]),
        ("SYS-WB13-1.ADF", "Shell.info", &[0xE3, 0x10]),
        // Bitmap font descriptor: FontContents, 0x0F00.
        ("SYS-WB31-6.ADF", "courier.font", &[0x0F, 0x00]),
    ];

    for (image, name, magic) in cases {
        let Some(mut reader) = open(&dir, image) else {
            continue;
        };
        let Ok(mut fs) = AmigaFs::mount(&mut reader, DD_TRACKS) else {
            continue;
        };
        let root = fs.root_block_num();
        let entry = fs
            .find_entry(root, name)
            .unwrap_or_else(|e| panic!("{}: find_entry({:?}) failed: {}", image, name, e))
            .unwrap_or_else(|| panic!("{}: {:?} not found", image, name));
        let data = fs
            .read_file(entry.block)
            .unwrap_or_else(|e| panic!("{}: read_file({:?}) failed: {}", image, name, e));
        assert!(
            data.starts_with(magic),
            "{}: {:?} starts with {:02X?}, expected magic {:02X?}",
            image,
            name,
            &data[..magic.len().min(data.len())],
            magic
        );
    }
}
