//! Opcode pattern definitions for the m68k disassembler.

/// Parser types for instruction operand layouts.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParserType {
    None,
    Move,
    Movea,
    Moveq,
    MovemRm,
    MovemMr,
    EaReg,
    RegEa,
    Adda,
    ImmEa,
    Quick,
    SingleEa,
    Branch,
    Dbcc,
    Scc,
    BitReg,
    BitImm,
    ShiftReg,
    ShiftMem,
    Exg,
    Ext,
    Link,
    Unlk,
    Trap,
    Swap,
    Chk,
    Lea,
    AbcdSbcd,
    MoveToCcr,
    MoveFromSr,
    MoveToSr,
    ImmCcr,
    ImmSr,
    Tst,
    Jsr,
    Jmp,
    Pea,
    Clr,
    Neg,
    Negx,
    Not,
    Nbcd,
    Tas,
    Nop,
    Rts,
    Rte,
    Rtr,
    Trapv,
    Illegal,
    Reset,
    Stop,
    MoveUsp,
    Cmpa,
    Cmpi,
    Cmpm,
    Cmp,
    Muls,
    Mulu,
    Divs,
    Divu,
    Eor,
    Rtd,
    Bkpt,
    Movep,
    Bsr,
    Bcc,
}

use crate::ea_categories::ea::*;

/// An opcode pattern with mask, match value, mnemonic, and EA categories.
#[derive(Debug, Clone)]
pub struct OpcodePattern {
    pub mask: u16,
    pub value: u16,
    pub mnemonic: &'static str,
    pub src_ea: u16,
    pub dst_ea: u16,
    pub cpu: &'static str,
    pub parser: ParserType,
    pub fixed_size: Option<&'static str>,
}

impl OpcodePattern {
    pub fn matches(&self, opcode: u16) -> bool {
        (opcode & self.mask) == self.value
    }
}

/// All known m68k opcode patterns.
pub fn opcode_patterns() -> &'static [OpcodePattern] {
    &[
        OpcodePattern {
            mask: 0xF100,
            value: 0xC100,
            mnemonic: "ABCD",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::AbcdSbcd,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0xD000,
            mnemonic: "ADD",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::EaReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xD0C0,
            mnemonic: "ADD",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xD0C0,
            mnemonic: "ADDA",
            src_ea: DATA,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Adda,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x5000,
            mnemonic: "ADDQ",
            src_ea: DATA,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Quick,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF130,
            value: 0xD100,
            mnemonic: "ADDX",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0xC000,
            mnemonic: "AND",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::EaReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xC0C0,
            mnemonic: "AND",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xE100,
            mnemonic: "ASL",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xE000,
            mnemonic: "ASR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xE108,
            mnemonic: "LSL",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xE008,
            mnemonic: "LSR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xE118,
            mnemonic: "ROL",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xE018,
            mnemonic: "ROR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xE110,
            mnemonic: "ROXL",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xE010,
            mnemonic: "ROXR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE1C0,
            mnemonic: "ASL",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE0C0,
            mnemonic: "ASR",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE1C8,
            mnemonic: "LSL",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE0C8,
            mnemonic: "LSR",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE1D8,
            mnemonic: "ROL",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE0D8,
            mnemonic: "ROR",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE1D0,
            mnemonic: "ROXL",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE0D0,
            mnemonic: "ROXR",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x6000,
            mnemonic: "Bcc",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Branch,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x0140,
            mnemonic: "BCHG",
            src_ea: DREG,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x0180,
            mnemonic: "BCLR",
            src_ea: DREG,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x01C0,
            mnemonic: "BSET",
            src_ea: DREG,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x0100,
            mnemonic: "BTST",
            src_ea: DREG,
            dst_ea: DATA,
            cpu: "68000",
            parser: ParserType::BitReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0840,
            mnemonic: "BCHG",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitImm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0880,
            mnemonic: "BCLR",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitImm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x08C0,
            mnemonic: "BSET",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitImm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0800,
            mnemonic: "BTST",
            src_ea: IMM,
            dst_ea: DATA,
            cpu: "68000",
            parser: ParserType::BitImm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x6100,
            mnemonic: "BRA",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Bsr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x4180,
            mnemonic: "CHK",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Chk,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x4200,
            mnemonic: "CLR",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Clr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0xB000,
            mnemonic: "CMP",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Cmp,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xB0C0,
            mnemonic: "CMP",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xB0C0,
            mnemonic: "CMPA",
            src_ea: DATA,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Cmpa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0C00,
            mnemonic: "CMPI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Cmpi,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xB108,
            mnemonic: "CMPM",
            src_ea: APOSTINC,
            dst_ea: APOSTINC,
            cpu: "68000",
            parser: ParserType::Cmpm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x5100,
            mnemonic: "DBcc",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Dbcc,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x81C0,
            mnemonic: "DIVS",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Divs,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x80C0,
            mnemonic: "DIVU",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Divu,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xB1C0,
            mnemonic: "EOR",
            src_ea: DREG,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Eor,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xC140,
            mnemonic: "EXG",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Exg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xC180,
            mnemonic: "EXG",
            src_ea: AREG,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Exg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xC188,
            mnemonic: "EXG",
            src_ea: DREG,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Exg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4880,
            mnemonic: "EXT",
            src_ea: 0,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Ext,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4EC0,
            mnemonic: "JMP",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Jmp,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4E80,
            mnemonic: "JSR",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Jsr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x41C0,
            mnemonic: "LEA",
            src_ea: CONTROL,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Lea,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF8,
            value: 0x4E50,
            mnemonic: "LINK",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Link,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF000,
            value: 0x3000,
            mnemonic: "MOVE",
            src_ea: ALL,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Move,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF000,
            value: 0x3000,
            mnemonic: "MOVEA",
            src_ea: DATA,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Movea,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x44C0,
            mnemonic: "MOVE",
            src_ea: DATA,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::MoveToCcr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x40C0,
            mnemonic: "MOVE",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::MoveFromSr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x46C0,
            mnemonic: "MOVE",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::MoveToSr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4840,
            mnemonic: "MOVEM",
            src_ea: DREG,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::MovemRm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4880,
            mnemonic: "MOVEM",
            src_ea: DREG,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::MovemRm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4C40,
            mnemonic: "MOVEM",
            src_ea: MEMORY,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::MovemMr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4C80,
            mnemonic: "MOVEM",
            src_ea: MEMORY,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::MovemMr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x7000,
            mnemonic: "MOVEQ",
            src_ea: 0,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Moveq,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF8,
            value: 0x4E60,
            mnemonic: "MOVE",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68010",
            parser: ParserType::MoveUsp,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0x0108,
            mnemonic: "MOVEP",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Movep,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xC1C0,
            mnemonic: "MULS",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Muls,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xC0C0,
            mnemonic: "MULU",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Mulu,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4800,
            mnemonic: "NBCD",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Nbcd,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4400,
            mnemonic: "NEG",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Neg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4000,
            mnemonic: "NEGX",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Negx,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E71,
            mnemonic: "NOP",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Nop,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4600,
            mnemonic: "NOT",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Not,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0x8000,
            mnemonic: "OR",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::EaReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x80C0,
            mnemonic: "OR",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4840,
            mnemonic: "PEA",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Pea,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E70,
            mnemonic: "RESET",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Reset,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E73,
            mnemonic: "RTE",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Rte,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E77,
            mnemonic: "RTR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Rtr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E75,
            mnemonic: "RTS",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Rts,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E74,
            mnemonic: "RTD",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68010",
            parser: ParserType::Rtd,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x8100,
            mnemonic: "SBCD",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::AbcdSbcd,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x50C0,
            mnemonic: "Scc",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Scc,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E72,
            mnemonic: "STOP",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Stop,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0x9000,
            mnemonic: "SUB",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::EaReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x90C0,
            mnemonic: "SUB",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x90C0,
            mnemonic: "SUBA",
            src_ea: DATA,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Adda,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x5100,
            mnemonic: "SUBQ",
            src_ea: DATA,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Quick,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF130,
            value: 0x9100,
            mnemonic: "SUBX",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF8,
            value: 0x4840,
            mnemonic: "SWAP",
            src_ea: 0,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Swap,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4AC0,
            mnemonic: "TAS",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Tas,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF0,
            value: 0x4E40,
            mnemonic: "TRAP",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Trap,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E76,
            mnemonic: "TRAPV",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Trapv,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4A00,
            mnemonic: "TST",
            src_ea: 0,
            dst_ea: DATA,
            cpu: "68000",
            parser: ParserType::Tst,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF8,
            value: 0x4E58,
            mnemonic: "UNLK",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Unlk,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x023C,
            mnemonic: "ANDI",
            src_ea: IMM,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ImmCcr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x027C,
            mnemonic: "ORI",
            src_ea: IMM,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ImmCcr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x0A3C,
            mnemonic: "EORI",
            src_ea: IMM,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ImmCcr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0600,
            mnemonic: "ADDI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0400,
            mnemonic: "SUBI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0200,
            mnemonic: "ANDI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0000,
            mnemonic: "ORI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0A00,
            mnemonic: "EORI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF8,
            value: 0x4848,
            mnemonic: "BKPT",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::Bkpt,
            fixed_size: None,
        },
    ]
}
