//! Opcode pattern definitions for the m68k disassembler.

/// Parser types for instruction operand layouts.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParserType {
    None,
    Move,
    Movea,
    Moveq,
    MovemRm,
    MovemMr,
    EaReg,
    RegEa,
    AddxSubx,
    Extb,
    PackUnpk,
    Lpstop,
    Adda,
    ImmEa,
    Quick,
    SingleEa,
    Branch,
    Dbcc,
    Scc,
    BitReg,
    BitImm,
    ShiftReg,
    ShiftMem,
    Exg,
    Ext,
    Link,
    Unlk,
    Trap,
    Swap,
    Chk,
    Lea,
    AbcdSbcd,
    MoveToCcr,
    MoveFromSr,
    MoveToSr,
    ImmCcr,
    ImmSr,
    Tst,
    Jsr,
    Jmp,
    Pea,
    Clr,
    Neg,
    Negx,
    Not,
    Nbcd,
    Tas,
    Nop,
    Rts,
    Rte,
    Rtr,
    Trapv,
    Illegal,
    Reset,
    Stop,
    MoveUsp,
    Cmpa,
    Cmpi,
    Cmpm,
    Cmp,
    Muls,
    Mulu,
    Divs,
    Divu,
    Eor,
    Rtd,
    Bkpt,
    MulLong,
    DivLong,
    Cas,
    Chk2Cmp2,
    Trapcc,
    Rtm,
    Callm,
    Moves,
    Move16,
    PSaveRestore,
    MovecFromCr,
    MovecToCr,
    Movep,
    Bitfield,
    Pmove,
    PflushFamily040,
    /// PLPAR/PLPAW (68060): single `(An)` operand, direction in bit 6.
    Plpa,
    CacheOp040,
    Fpu,
    FpuScc,
    FpuDbcc,
    FpuTrapcc,
    FpuBcc,
    FpuSave,
    FpuRestore,
    LinkLong,
}

use crate::ea_categories::ea::*;

/// An opcode pattern with mask, match value, mnemonic, and EA categories.
#[derive(Debug, Clone)]
pub struct OpcodePattern {
    pub mask: u16,
    pub value: u16,
    pub mnemonic: &'static str,
    pub src_ea: u16,
    pub dst_ea: u16,
    pub cpu: &'static str,
    pub parser: ParserType,
    pub fixed_size: Option<&'static str>,
}

impl OpcodePattern {
    pub fn matches(&self, opcode: u16) -> bool {
        (opcode & self.mask) == self.value
    }
}

/// All known m68k opcode patterns.
pub fn opcode_patterns() -> &'static [OpcodePattern] {
    &[
        OpcodePattern {
            // EXG opmode field is bits 7-3 (PRM: 01000=Dn,Dn, 01001=An,An,
            // 10001=Dn,An) - the mask must cover all 5 opmode bits, not just
            // bits 7-6, otherwise these three EXG forms collide with each
            // other (and, with a mask this narrow, would also fall inside
            // AND's wider 0xF100/0xC100 range). Verified against real
            // reference output: exg d0,d1 -> 0xC141, exg a0,a1 ->
            // 0xC149, exg d2,a3 -> 0xC58B.
            mask: 0xF1F8,
            value: 0xC140,
            mnemonic: "EXG",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Exg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xC148,
            mnemonic: "EXG",
            src_ea: AREG,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Exg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0xC188,
            mnemonic: "EXG",
            src_ea: DREG,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Exg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F0,
            value: 0xC100,
            mnemonic: "ABCD",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::AbcdSbcd,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF0C0,
            value: 0xD0C0,
            mnemonic: "ADDA",
            src_ea: DATA,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Adda,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF130,
            value: 0xD100,
            mnemonic: "ADDX",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::AddxSubx,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0xD100,
            mnemonic: "ADD",
            src_ea: DREG,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0xD000,
            mnemonic: "ADD",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::EaReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0xC000,
            mnemonic: "AND",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::EaReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0xC100,
            mnemonic: "AND",
            src_ea: DREG,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE1C0,
            mnemonic: "ASL",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE0C0,
            mnemonic: "ASR",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE3C0,
            mnemonic: "LSL",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE2C0,
            mnemonic: "LSR",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE7C0,
            mnemonic: "ROL",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE6C0,
            mnemonic: "ROR",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE5C0,
            mnemonic: "ROXL",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0xE4C0,
            mnemonic: "ROXR",
            src_ea: 0,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::ShiftMem,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF118,
            value: 0xE100,
            mnemonic: "ASL",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF118,
            value: 0xE000,
            mnemonic: "ASR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF118,
            value: 0xE108,
            mnemonic: "LSL",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF118,
            value: 0xE008,
            mnemonic: "LSR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF118,
            value: 0xE118,
            mnemonic: "ROL",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF118,
            value: 0xE018,
            mnemonic: "ROR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF118,
            value: 0xE110,
            mnemonic: "ROXL",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF118,
            value: 0xE010,
            mnemonic: "ROXR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ShiftReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF000,
            value: 0x6000,
            mnemonic: "Bcc",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Branch,
            fixed_size: None,
        },
        OpcodePattern {
            // MOVEP Dn,(d16,An) / (d16,An),Dn: all four size/direction opmodes
            // (4=word mem->reg, 5=long mem->reg, 6=word reg->mem, 7=long reg->mem,
            // encoded in bits 7-6 with bit 8 fixed at 1) share this bit pattern.
            // Must precede the BTST/BCHG/BCLR/BSET Dn,<ea> patterns below, whose
            // wider 0xF1C0 mask would otherwise swallow every MOVEP opmode (bits
            // 7-6 are exactly what distinguishes BTST/BCHG/BCLR/BSET from each
            // other) - verified against reference output for all four
            // MOVEP forms.
            mask: 0xF138,
            value: 0x0108,
            mnemonic: "MOVEP",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Movep,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x0140,
            mnemonic: "BCHG",
            src_ea: DREG,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x0180,
            mnemonic: "BCLR",
            src_ea: DREG,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x01C0,
            mnemonic: "BSET",
            src_ea: DREG,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x0100,
            mnemonic: "BTST",
            src_ea: DREG,
            dst_ea: DATA,
            cpu: "68000",
            parser: ParserType::BitReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x0840,
            mnemonic: "BCHG",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitImm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x0880,
            mnemonic: "BCLR",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitImm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x08C0,
            mnemonic: "BSET",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::BitImm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x0800,
            mnemonic: "BTST",
            src_ea: IMM,
            dst_ea: DATA,
            cpu: "68000",
            parser: ParserType::BitImm,
            fixed_size: None,
        },
        // CHK.W — size bits 8-7 = 11. The long form below has 10; masking
        // both out would also match the 00/01 encodings, which are not CHK.
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x4180,
            mnemonic: "CHK",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Chk,
            fixed_size: Some("w"),
        },
        // CHK.L (68020+). Without this pattern the long form decoded as a
        // data word, so `CHK.L` did not round-trip at all.
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x4100,
            mnemonic: "CHK",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68020",
            parser: ParserType::Chk,
            fixed_size: Some("l"),
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x4200,
            mnemonic: "CLR",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Clr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0xB000,
            mnemonic: "CMP",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Cmp,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF0C0,
            value: 0xB0C0,
            mnemonic: "CMPA",
            src_ea: DATA,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Cmpa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0C00,
            mnemonic: "CMPI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Cmpi,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF138,
            value: 0xB108,
            mnemonic: "CMPM",
            src_ea: APOSTINC,
            dst_ea: APOSTINC,
            cpu: "68000",
            parser: ParserType::Cmpm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF0F8,
            value: 0x50C8,
            mnemonic: "DBcc",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Dbcc,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x81C0,
            mnemonic: "DIVS",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Divs,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x80C0,
            mnemonic: "DIVU",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Divu,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0xB100,
            mnemonic: "EOR",
            src_ea: DREG,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Eor,
            fixed_size: None,
        },
        OpcodePattern {
            // EXTB.L (68020+): 0x49C0 | Dn — a separate opmode (bits 8-6
            // = 111) from EXT.W/EXT.L, so the EXT pattern below (mask
            // 0xFFB8, which pins bit 8 to 0) never matches it. Without
            // this entry `extb.l d0` decoded as `lea d0,a4`.
            mask: 0xFFF8,
            value: 0x49C0,
            mnemonic: "EXTB",
            src_ea: 0,
            dst_ea: DREG,
            cpu: "68020",
            parser: ParserType::Extb,
            fixed_size: None,
        },
        OpcodePattern {
            // PACK/UNPK (68020+): 0x8140/0x8180 | ... with bit 3 selecting
            // the predecrement-memory form, followed by a 16-bit
            // adjustment word. Both must precede the OR patterns
            // (0x8000/0xF100), which cover this range.
            mask: 0xF1F8,
            value: 0x8140,
            mnemonic: "PACK",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::PackUnpk,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0x8148,
            mnemonic: "PACK",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::PackUnpk,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0x8180,
            mnemonic: "UNPK",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::PackUnpk,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F8,
            value: 0x8188,
            mnemonic: "UNPK",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::PackUnpk,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFB8,
            value: 0x4880,
            mnemonic: "EXT",
            src_ea: 0,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Ext,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4EC0,
            mnemonic: "JMP",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Jmp,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4E80,
            mnemonic: "JSR",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Jsr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0x41C0,
            mnemonic: "LEA",
            src_ea: CONTROL,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Lea,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF8,
            value: 0x4E50,
            mnemonic: "LINK",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Link,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x003C,
            mnemonic: "ORI",
            src_ea: IMM,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ImmCcr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x007C,
            mnemonic: "ORI",
            src_ea: IMM,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ImmSr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x023C,
            mnemonic: "ANDI",
            src_ea: IMM,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ImmCcr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x027C,
            mnemonic: "ANDI",
            src_ea: IMM,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ImmSr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x0A3C,
            mnemonic: "EORI",
            src_ea: IMM,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ImmCcr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x0A7C,
            mnemonic: "EORI",
            src_ea: IMM,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::ImmSr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0600,
            mnemonic: "ADDI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0400,
            mnemonic: "SUBI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0200,
            mnemonic: "ANDI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0000,
            mnemonic: "ORI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x0A00,
            mnemonic: "EORI",
            src_ea: IMM,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::ImmEa,
            fixed_size: None,
        },
        OpcodePattern {
            // BFTST/BFEXTU/BFCHG/BFEXTS/BFCLR/BFFFO/BFSET/BFINS: the
            // instruction name and destination-register operand depend on
            // the extension word's subtype field (bits 10-8), not on the
            // opcode word itself, so the mnemonic below is a placeholder
            // the Bitfield parser always overrides.
            mask: 0xF8C0,
            value: 0xE8C0,
            mnemonic: "BF",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::Bitfield,
            fixed_size: None,
        },
        OpcodePattern {
            // PMOVE/PFLUSH/PFLUSHA/PTESTR/PTESTW (68030+ MMU): all share
            // the 0xF000-0xF03F opword range (EA mode/register in bits
            // 5-0); the actual instruction and its operands depend on the
            // extension word's group-prefix field (bits 15-13), which the
            // Pmmu parser reads and dispatches on. Placeholder mnemonic,
            // like the Bitfield entry above.
            mask: 0xFFC0,
            value: 0xF000,
            mnemonic: "PMMU",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68030",
            parser: ParserType::Pmove,
            fixed_size: None,
        },
        OpcodePattern {
            // 68040 PFLUSH family: PFLUSHN(An)/PFLUSH(An)/PFLUSHAN/PFLUSHA,
            // sharing base 0xF500 with a 2-bit opmode at bits 4-3 (00/01/
            // 10/11) and register at bits 2-0. Verified against real
            // reference output (F500/F508/F510/F518). Placeholder
            // mnemonic; PflushFamily040 always overrides it.
            mask: 0xFFE0,
            value: 0xF500,
            mnemonic: "PFLUSH",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68040",
            parser: ParserType::PflushFamily040,
            fixed_size: None,
        },
        OpcodePattern {
            // PLPAR (68060): load physical address, read. Base 0xF5C8,
            // address register in bits 2-0. Must precede the CACHE
            // pattern below, whose 0xFC00/0xF400 mask covers this range
            // and would otherwise decode it as `cinvl bc,(An)` — the
            // assembler encodes PLPAR/PLPAW correctly, so without these
            // two entries the roundtrip is broken.
            // Verified against reference output: `plpar (a0)` -> F5C8,
            // `plpar (a3)` -> F5CB.
            mask: 0xFFF8,
            value: 0xF5C8,
            mnemonic: "PLPAR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68060",
            parser: ParserType::Plpa,
            fixed_size: None,
        },
        OpcodePattern {
            // PLPAW (68060): load physical address, write. Base 0xF588 —
            // bit 6 distinguishes it from PLPAR.
            // Verified: `plpaw (a0)` -> F588, `plpaw (a3)` -> F58B.
            mask: 0xFFF8,
            value: 0xF588,
            mnemonic: "PLPAW",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68060",
            parser: ParserType::Plpa,
            fixed_size: None,
        },
        OpcodePattern {
            // 68040 cache invalidate/push family: CINVL/CINVP/CINVA/
            // CPUSHL/CPUSHP/CPUSHA, sharing base 0xF400 with a 2-bit scope
            // (bits 7-6: 01=DC,10=IC,11=BC), push flag (bit 5), 2-bit unit
            // (bits 4-3: 01=Line,10=Page,11=All), and register (bits 2-0,
            // only meaningful for the Line/Page forms). Verified against
            // reference output for all eight scope/unit
            // combinations. Placeholder mnemonic; CacheOp040 overrides it.
            mask: 0xFC00,
            value: 0xF400,
            mnemonic: "CACHE",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68040",
            parser: ParserType::CacheOp040,
            fixed_size: None,
        },
        OpcodePattern {
            // FDBcc Dn,label (68020/68881+): base 0xF248, register in bits 2-0. Must be
            // listed before the FScc/FBcc-family entries below since 0xF248-0xF24F falls
            // inside FScc's 0xF240/0xFFC0 range. Placeholder mnemonic; FpuDbcc overrides it.
            mask: 0xFFF8,
            value: 0xF248,
            mnemonic: "FDBcc",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::FpuDbcc,
            fixed_size: None,
        },
        OpcodePattern {
            // FTRAPcc (68020/68881+): base 0xF278, mode in bits 2-0 (2=word operand,
            // 3=long operand, 4=no operand). Must be listed before FScc for the same
            // range-overlap reason as FDBcc above. Placeholder mnemonic; FpuTrapcc overrides it.
            mask: 0xFFF8,
            value: 0xF278,
            mnemonic: "FTRAPcc",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::FpuTrapcc,
            fixed_size: None,
        },
        OpcodePattern {
            // FScc <ea> (68020/68881+): base 0xF240, EA mode/register in bits 5-0,
            // condition in the extension word. Placeholder mnemonic; FpuScc overrides it.
            mask: 0xFFC0,
            value: 0xF240,
            mnemonic: "FScc",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::FpuScc,
            fixed_size: None,
        },
        OpcodePattern {
            // FBcc (68020/68881+): base 0xF280, size bit 6 (0=word,1=long displacement),
            // condition in bits 4-0. mask must leave bit 6 free so both size forms match
            // this one pattern (verified against reference output for `fbeq.l`, which
            // encodes as 0xF2C1, not 0xF281). Placeholder mnemonic; FpuBcc overrides it.
            mask: 0xFF80,
            value: 0xF280,
            mnemonic: "FBcc",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::FpuBcc,
            fixed_size: None,
        },
        OpcodePattern {
            // FSAVE <ea> (68020/68881+): base 0xF300, EA mode/register in bits 5-0.
            mask: 0xFFC0,
            value: 0xF300,
            mnemonic: "FSAVE",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::FpuSave,
            fixed_size: None,
        },
        OpcodePattern {
            // FRESTORE <ea> (68020/68881+): base 0xF340, EA mode/register in bits 5-0.
            mask: 0xFFC0,
            value: 0xF340,
            mnemonic: "FRESTORE",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::FpuRestore,
            fixed_size: None,
        },
        OpcodePattern {
            // FPU cpGEN group (68020/68881+): FADD/FMOVE/FMOVECR/FSINCOS/FMOVEM/... all
            // share base 0xF200, EA mode/register in bits 5-0; the actual instruction and
            // its operands depend entirely on the extension word (bits 15-13 select the
            // instruction group, bits 6-0 select the arithmetic opclass within cpGEN
            // itself). Placeholder mnemonic; Fpu parser overrides it.
            mask: 0xFFC0,
            value: 0xF200,
            mnemonic: "FPU",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::Fpu,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xE1C0,
            value: 0x2040,
            mnemonic: "MOVEA",
            src_ea: DATA,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Movea,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF000,
            value: 0x1000,
            mnemonic: "MOVE",
            src_ea: ALL,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Move,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF000,
            value: 0x2000,
            mnemonic: "MOVE",
            src_ea: ALL,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Move,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF000,
            value: 0x3000,
            mnemonic: "MOVE",
            src_ea: ALL,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Move,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x44C0,
            mnemonic: "MOVE",
            src_ea: DATA,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::MoveToCcr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x40C0,
            mnemonic: "MOVE",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::MoveFromSr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x46C0,
            mnemonic: "MOVE",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::MoveToSr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF80,
            value: 0x4880,
            mnemonic: "MOVEM",
            src_ea: DREG,
            dst_ea: MEMORY,
            cpu: "68000",
            parser: ParserType::MovemRm,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF80,
            value: 0x4C80,
            mnemonic: "MOVEM",
            src_ea: MEMORY,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::MovemMr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0x7000,
            mnemonic: "MOVEQ",
            src_ea: 0,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Moveq,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF0,
            value: 0x4E60,
            mnemonic: "MOVE",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::MoveUsp,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xC1C0,
            mnemonic: "MULS",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Muls,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1C0,
            value: 0xC0C0,
            mnemonic: "MULU",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Mulu,
            fixed_size: None,
        },
        OpcodePattern {
            // LINK.L An,#disp32 (68020+): own base opcode 0x4808, unrelated to
            // LINK.W's 0x4E50. Shares NBCD's 0x4800-0x483F range (An-direct mode
            // is invalid for NBCD's alterable-memory EA, but NBCD's mask alone
            // doesn't exclude it), so must precede NBCD here.
            mask: 0xFFF8,
            value: 0x4808,
            mnemonic: "LINK",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::LinkLong,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4800,
            mnemonic: "NBCD",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Nbcd,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x4400,
            mnemonic: "NEG",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Neg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x4000,
            mnemonic: "NEGX",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Negx,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E71,
            mnemonic: "NOP",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Nop,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4AFC,
            mnemonic: "ILLEGAL",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Illegal,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x4600,
            mnemonic: "NOT",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Not,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF1F0,
            value: 0x8100,
            mnemonic: "SBCD",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::AbcdSbcd,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0x8000,
            mnemonic: "OR",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::EaReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0x8100,
            mnemonic: "OR",
            src_ea: DREG,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF8,
            value: 0x4840,
            mnemonic: "SWAP",
            src_ea: 0,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::Swap,
            fixed_size: None,
        },
        OpcodePattern {
            // BKPT #vector (68010+): shares PEA's 0xFFC0/0x4840 range (both
            // sit inside the 0x4840-0x487F "Miscellaneous" block) and must
            // precede it here, the same way SWAP above does - otherwise
            // every BKPT opcode is swallowed by PEA's wider mask.
            mask: 0xFFF8,
            value: 0x4848,
            mnemonic: "BKPT",
            src_ea: 0,
            dst_ea: 0,
            // BKPT is a 68010 addition, not 68020 — with the level set
            // too high the pattern was filtered out on `--cpu 68010` and
            // the opcode fell through to PEA (`bkpt #3` -> `pea a3`).
            // Matches the assembler side, which gates BKPT at 68010.
            cpu: "68010",
            parser: ParserType::Bkpt,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4840,
            mnemonic: "PEA",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Pea,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E70,
            mnemonic: "RESET",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Reset,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E73,
            mnemonic: "RTE",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Rte,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E77,
            mnemonic: "RTR",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Rtr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E75,
            mnemonic: "RTS",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Rts,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E74,
            mnemonic: "RTD",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68010",
            parser: ParserType::Rtd,
            fixed_size: None,
        },
        OpcodePattern {
            // TRAPcc (68020+): 0x50F8|(cc<<8) with opword bits 2-0 = 4
            // (no operand), 0x50FA = 2 (word immediate), 0x50FB = 3
            // (long). Shares the 0x5xxx range with Scc below and must be
            // listed first — Scc's mask (0xF0C0) also matches these.
            mask: 0xF0F8,
            value: 0x50F8,
            mnemonic: "TRAPcc",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::Trapcc,
            fixed_size: None,
        },
        OpcodePattern {
            // Scc: 0x50C0 | (cc << 8) | ea. The condition occupies bits
            // 11-8, so the mask must leave those free (0xF0C0) — with the
            // previous 0xFFC0 it pinned cc to 0, i.e. only `ST` matched
            // and the other 15 conditions (SF/SEQ/SNE/...) fell through
            // to the data-word fallback. Must stay *after* the DBcc
            // pattern (0x50C8/0xF0F8), whose range 0x5xC8-0x5xCF this
            // one would otherwise swallow: DBcc is Scc's mode-1 encoding.
            mask: 0xF0C0,
            value: 0x50C0,
            mnemonic: "Scc",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Scc,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0x5000,
            mnemonic: "ADDQ",
            src_ea: DATA,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Quick,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E72,
            mnemonic: "STOP",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Stop,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF0C0,
            value: 0x90C0,
            mnemonic: "SUBA",
            src_ea: DATA,
            dst_ea: AREG,
            cpu: "68000",
            parser: ParserType::Adda,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0x5100,
            mnemonic: "SUBQ",
            src_ea: DATA,
            dst_ea: ALL,
            cpu: "68000",
            parser: ParserType::Quick,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF130,
            value: 0x9100,
            mnemonic: "SUBX",
            src_ea: DREG,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::AddxSubx,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0x9100,
            mnemonic: "SUB",
            src_ea: DREG,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::RegEa,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xF100,
            value: 0x9000,
            mnemonic: "SUB",
            src_ea: DATA,
            dst_ea: DREG,
            cpu: "68000",
            parser: ParserType::EaReg,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x4AC0,
            mnemonic: "TAS",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68000",
            parser: ParserType::Tas,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF0,
            value: 0x4E40,
            mnemonic: "TRAP",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Trap,
            fixed_size: None,
        },
        // --- 68020+ instructions that previously had no decoder pattern
        // at all (the assembler emitted them, but disassembling the result
        // produced `dc.w`). Placed before the generic 0x4Exx/0x4Cxx
        // patterns they would otherwise be swallowed by.
        OpcodePattern {
            // MULU.L/MULS.L: 0x4C00 | ea, extension word carries Dq
            // (bits 14-12), signed flag (bit 11), 64-bit form (bit 10)
            // and Dr (bits 2-0).
            mask: 0xFFC0,
            value: 0x4C00,
            mnemonic: "MUL",
            src_ea: DATA,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::MulLong,
            fixed_size: None,
        },
        OpcodePattern {
            // DIVU.L/DIVS.L/DIVUL.L/DIVSL.L: 0x4C40 | ea. DIVxL (separate
            // remainder/quotient registers) is distinguished from plain
            // DIVx.L not by a bit of its own but by Dr != Dq with the
            // 64-bit bit clear — see the parser.
            mask: 0xFFC0,
            value: 0x4C40,
            mnemonic: "DIV",
            src_ea: DATA,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::DivLong,
            fixed_size: None,
        },
        // CAS.B/W/L: bases 0x0AC0/0x0CC0/0x0EC0 (size in opword bits
        // 10-9). One pattern per size rather than a shared mask leaving
        // bits 10-9 free: BSET's immediate form is 0x08C0, i.e. the same
        // shape with bits 10-9 = 00, so a size-agnostic CAS mask would
        // also match BSET (and, being listed later, lose to it anyway).
        // These must also precede the MOVES pattern below, whose 0xFF00
        // mask covers CAS.L's 0x0Exx range.
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x0AC0,
            mnemonic: "CAS",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68020",
            parser: ParserType::Cas,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x0CC0,
            mnemonic: "CAS",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68020",
            parser: ParserType::Cas,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFC0,
            value: 0x0EC0,
            mnemonic: "CAS",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68020",
            parser: ParserType::Cas,
            fixed_size: None,
        },
        OpcodePattern {
            // MOVES: 0x0E00 | (size << 9) | ea, ext word bit 11 =
            // direction. Listed after CAS.L (0x0EC0), which this mask
            // would otherwise swallow.
            mask: 0xFF00,
            value: 0x0E00,
            mnemonic: "MOVES",
            src_ea: 0,
            dst_ea: ALTERABLE_MEMORY,
            cpu: "68010",
            parser: ParserType::Moves,
            fixed_size: None,
        },
        OpcodePattern {
            // CHK2/CMP2: 0x00C0 | (size << 9) | ea; ext word bit 11
            // selects CHK2 (1) vs CMP2 (0).
            mask: 0xF9C0,
            value: 0x00C0,
            mnemonic: "CMP2",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::Chk2Cmp2,
            fixed_size: None,
        },
        OpcodePattern {
            // RTM: 0x06C0 | reg (bit 3 selects Dn vs An).
            mask: 0xFFF0,
            value: 0x06C0,
            mnemonic: "RTM",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::Rtm,
            fixed_size: None,
        },
        OpcodePattern {
            // CALLM: 0x06C0 | ea — same base as RTM but with a mode
            // field other than 0/1, so RTM (0xFFF0) must come first.
            mask: 0xFFC0,
            value: 0x06C0,
            mnemonic: "CALLM",
            src_ea: CONTROL,
            dst_ea: 0,
            cpu: "68020",
            parser: ParserType::Callm,
            fixed_size: None,
        },
        OpcodePattern {
            // MOVE16 (68040+): 0xF620 | reg for the (An)+,(An)+ form.
            mask: 0xFFE0,
            value: 0xF620,
            mnemonic: "MOVE16",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68040",
            parser: ParserType::Move16,
            fixed_size: None,
        },
        OpcodePattern {
            // LPSTOP #sr (68060): fixed three-word form 0xF800 0x01C0
            // <sr>. Listed before the PSAVE/FPU patterns in the 0xFxxx
            // range so its exact opword isn't absorbed by a wider mask.
            mask: 0xFFFF,
            value: 0xF800,
            mnemonic: "LPSTOP",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68060",
            parser: ParserType::Lpstop,
            fixed_size: None,
        },
        OpcodePattern {
            // PSAVE (0xF100) / PRESTORE (0xF140), 68030+ MMU state
            // save/restore. Must precede the generic FPU cpGEN pattern
            // (0xF200/0xFFC0) — different base, but the PMMU group
            // patterns nearby share the 0xF1xx range.
            mask: 0xFF80,
            value: 0xF100,
            mnemonic: "PSAVE",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68030",
            parser: ParserType::PSaveRestore,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFFF,
            value: 0x4E76,
            mnemonic: "TRAPV",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Trapv,
            fixed_size: None,
        },
        OpcodePattern {
            // MOVEC Cr,Rn (control register to general register). 68010+.
            mask: 0xFFFF,
            value: 0x4E7A,
            mnemonic: "MOVEC",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68010",
            parser: ParserType::MovecFromCr,
            fixed_size: None,
        },
        OpcodePattern {
            // MOVEC Rn,Cr (general register to control register). 68010+.
            mask: 0xFFFF,
            value: 0x4E7B,
            mnemonic: "MOVEC",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68010",
            parser: ParserType::MovecToCr,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFF00,
            value: 0x4A00,
            mnemonic: "TST",
            src_ea: 0,
            dst_ea: DATA,
            cpu: "68000",
            parser: ParserType::Tst,
            fixed_size: None,
        },
        OpcodePattern {
            mask: 0xFFF8,
            value: 0x4E58,
            mnemonic: "UNLK",
            src_ea: 0,
            dst_ea: 0,
            cpu: "68000",
            parser: ParserType::Unlk,
            fixed_size: None,
        },
    ]
}

/// FPU arithmetic opclass/opmode codes (extension word bits 6-0).
///
/// The single source of truth for both directions. The assembler and the
/// disassembler each used to carry their own copy, and six entries had
/// drifted apart from the hardware in *both* copies identically: `FTAN`
/// sat at 0x0B (unassigned) while 0x0F held `FTENTOX`, and the
/// exponential/logarithm group was rotated by one. Every affected
/// instruction assembled to a different but perfectly valid FPU operation
/// — `FETOX` emitting `FTWOTOX`, `FLOGN` emitting `FLOG10` — with no
/// diagnostic anywhere, because the two tables agreed with each other.
///
/// Verified entry by entry against the reference assembler.
pub const FPU_ARITH_OPS: &[(u16, &str)] = &[
    (0x00, "fmove"),
    (0x01, "fint"),
    (0x02, "fsinh"),
    (0x03, "fintrz"),
    (0x04, "fsqrt"),
    (0x06, "flognp1"),
    (0x08, "fetoxm1"),
    (0x09, "ftanh"),
    (0x0A, "fatan"),
    (0x0C, "fasin"),
    (0x0D, "fatanh"),
    (0x0E, "fsin"),
    (0x0F, "ftan"),
    (0x10, "fetox"),
    (0x11, "ftwotox"),
    (0x12, "ftentox"),
    (0x14, "flogn"),
    (0x15, "flog10"),
    (0x16, "flog2"),
    (0x18, "fabs"),
    (0x19, "fcosh"),
    (0x1A, "fneg"),
    (0x1C, "facos"),
    (0x1D, "fcos"),
    (0x1E, "fgetexp"),
    (0x1F, "fgetman"),
    (0x20, "fdiv"),
    (0x21, "fmod"),
    (0x22, "fadd"),
    (0x23, "fmul"),
    (0x24, "fsgldiv"),
    (0x25, "frem"),
    (0x26, "fscale"),
    (0x27, "fsglmul"),
    (0x28, "fsub"),
    (0x38, "fcmp"),
    (0x3A, "ftst"),
];

/// Opcode for an FPU arithmetic mnemonic (case-insensitive).
pub fn fpu_arith_code(mnemonic: &str) -> Option<u16> {
    FPU_ARITH_OPS
        .iter()
        .find(|(_, n)| n.eq_ignore_ascii_case(mnemonic))
        .map(|(c, _)| *c)
}

/// Mnemonic for an FPU arithmetic opcode.
pub fn fpu_arith_mnemonic(code: u16) -> Option<&'static str> {
    FPU_ARITH_OPS
        .iter()
        .find(|(c, _)| *c == code)
        .map(|(_, n)| *n)
}
